name: CI Tests

on: [pull_request,push]

jobs:
  Ubuntu:
    runs-on: ubuntu-${{ matrix.os_ver }}
    name: Ubuntu-${{ matrix.os_ver }}
    strategy:
      fail-fast: false
      matrix:
        os_ver: [22.04, 24.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prerequisties
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            qtbase5-dev \
            libqt5svg5-dev \
            qttools5-dev

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON

      - name: Building
        run: |
          make -j$(nproc) -C build

  MSVC:
    runs-on: windows-latest
    name: MSVC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-Qt-Cache

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.2
          cache: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configuring
        run: |
          mkdir build; cd build
          cmake .. -DBUILD_SHARED_LIBS=ON

      - name: Building
        run: |
          cmake --build build --config RelWithDebInfo -- -maxCpuCount

  MinGW-w64:
    runs-on: windows-latest
    name: MinGW-w64
    strategy:
      fail-fast: false
      matrix:
        msystem: [UCRT64, CLANG64]
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MinGW-w64 packages
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.msystem }}
          pacboy: >-
            cmake:p
            ninja:p
            cc:p
            qt5-base:p
            qt5-svg:p
            qt5-tools:p

      - name: Configuring
        run: |
          mkdir build && cd build
          cmake ..  -DBUILD_SHARED_LIBS=ON

      - name: Building
        run: |
          cmake --build build

  macos:
    runs-on: macos-latest
    name: macos
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        run: |
          brew list -1 | grep python | while read formula; do brew unlink $formula; brew link --overwrite $formula; done
          brew update
          brew install --display-times qt@5

      - name: Configuring
        run: |
          export PATH=$(brew --prefix)/opt/qt@5/bin:$PATH
          mkdir build && cd build
          cmake ..

      - name: Building
        run: |
          make -j$(sysctl -n hw.logicalcpu) -C build
